export const enum GatewayPoolsEnum {
  MINE = 'MINE',
  TERRA_WORLD = 'TERRA_WORLD',
  WHITE_WHALE = 'WHITE_WHALE',
  XDEFI = 'XDEFI',
  SAYVE = 'SAYVE',
  GLOW = 'GLOW',
  NEXUS = 'NEXUS',
  DEVIANTS_FACTIONS = 'DEVIANTS_FACTIONS',
  ORION = 'ORION',
  GALACTIC_PUNKS = 'GALACTIC_PUNKS',
  VALKYRIE = 'VALKYRIE',
  LOOP = 'LOOP',
}
