export const enum GatewayPoolsEnum {
  MINE = 'MINE',
  TERRA_WORLD = 'TERRA_WORLD',
  WHITE_WHALE = 'WHITE_WHALE',
  XDEFI = 'XDEFI',
  SAYVE = 'SAYVE',
  GLOW = 'GLOW',
  NEXUS = 'NEXUS',
  DEVIANTS_FACTIONS = 'DEVIANTS_FACTIONS',
  ORION = 'ORION',
  GALACTIC_PUNKS = 'GALACTIC_PUNKS',
  VALKYRIE = 'VALKYRIE',
  LOOP = 'LOOP',
  ARTS = 'ARTS',
  WCOIN = 'WCOIN',
  LUNA_BULLS = 'LUNA_BULLS',
  TERRA_BOTS = 'TERRA_BOTS',
}

export const enum GatewayPoolsSortBy {
  ALPHABETICAL = 'ALPHABETICAL',
  CLAIM_AT = 'CLAIM_AT',
}
