apiVersion: v1
kind: Service
metadata:
  name: {{ include "pylonboard.fullname" . }}
  labels:
    {{- include "pylonboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "pylonboard.selectorLabels" . | nindent 4 }}
